[tool.poetry]
name = "modelserver"
version = "0.2.0"
description = ""
authors = ["Andrew Duffy <andrew@intrinsiclabs.ai>"]
readme = "README.md"

[tool.poetry.scripts]
modelserver = "modelserver.app:entrypoint"
workerserver = "workerserver.worker:entrypoint"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.2"
fastapi = "^0.103.2"
llama-cpp-python = "^0.2.11"
huggingface-hub = "0.17.3"
duckdb = "^0.9.1"
uvicorn = "^0.23.2"
colorlog = "^6.7.0"
sqlalchemy = "^2.0.22"
websockets = "^11.0.3"
python-dotenv = "^1.0.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.0"
mypy = "^1.6.0"
mypy-extensions = "^1.0.0"
isort = "^5.12.0"
black = "^23.9.1"
pytest = "^7.4.2"


[tool.poetry.group.remoteworker.dependencies]
trl = "^0.7.2"
transformers = "^4.34.1"
httpx = "^0.25.0"
peft = "^0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
