name: Autorelease main with minor version bumps
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Autorelease Trigger
        id: autorelease
        uses: a10y/autorelease-action@0.3.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
