# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check for common spelling mistakes in docs or Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  spellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Scan code for common spelling errors
      run: |
        if [[ -z "$(grep -n -ri compleat frontend)" ]]; then
          exit 0;
        else
          exit 1;
        fi
